"""
This type stub file was generated by pyright.
"""

import networkx as nx

def empty_config() -> nx.DiGraph:
    ...

def default_config() -> nx.DiGraph:
    ...

def geo_config() -> nx.DiGraph:
    ...

def add_edge_config(g: nx.DiGraph) -> nx.DiGraph:
    ...

def add_node_config(g: nx.DiGraph) -> nx.DiGraph:
    ...

def add_geo_config(g: nx.DiGraph) -> nx.DiGraph:
    ...

def reroot_graph(G: nx.DiGraph, node: str) -> nx.DiGraph:
    """Return a copy of the graph rooted at the given node"""
    ...

