"""
This type stub file was generated by pyright.
"""

import pandas as pd
import geopandas as gpd

DEFAULT_CRS = ...
def build_shapes(df: pd.DataFrame) -> gpd.GeoDataFrame:
    ...

def build_stops(df: pd.DataFrame) -> gpd.GeoDataFrame:
    ...

