"""
This type stub file was generated by pyright.
"""

import networkx as nx
import pandas as pd
from typing import Optional, Union
from .types import View

class Feed:
    def __init__(
        self,
        source: Union[str, Feed],
        view: Optional[View] = ...,
        config: Optional[nx.DiGraph[str]] = ...,
    ) -> None: ...
    def get(self, filename: str) -> pd.DataFrame: ...
    def set(self, filename: str, df: pd.DataFrame) -> None: ...

    agency: pd.DataFrame
    calendar: pd.DataFrame
    calendar_dates: pd.DataFrame
    fare_attributes: pd.DataFrame
    fare_rules: pd.DataFrame
    feed_info: pd.DataFrame
    frequencies: pd.DataFrame
    routes: pd.DataFrame
    shapes: pd.DataFrame
    stops: pd.DataFrame
    stop_times: pd.DataFrame
    transfers: pd.DataFrame
    trips: pd.DataFrame
