"""
This type stub file was generated by pyright.
"""

import datetime
import networkx as nx
from typing import Dict, FrozenSet, Optional, Tuple
from .gtfs import Feed
from .types import View

DAY_NAMES = ...

def load_feed(
    path: str, view: Optional[View] = ..., config: Optional[nx.DiGraph[str]] = ...
) -> Feed: ...
def load_raw_feed(path: str) -> Feed: ...
def load_geo_feed(path: str, view: Optional[View] = ...) -> Feed: ...
def read_busiest_date(path: str) -> Tuple[datetime.date, FrozenSet[str]]:
    """Find the earliest date with the most trips"""
    ...

def read_busiest_week(path: str) -> Dict[datetime.date, FrozenSet[str]]:
    """Find the earliest week with the most trips"""
    ...

def read_service_ids_by_date(path: str) -> Dict[datetime.date, FrozenSet[str]]:
    """Find all service identifiers by date"""
    ...

def read_dates_by_service_ids(
    path: str,
) -> Dict[FrozenSet[str], FrozenSet[datetime.date]]:
    """Find dates with identical service"""
    ...

def read_trip_counts_by_date(path: str) -> Dict[datetime.date, int]:
    """A useful proxy for busyness"""
    ...
