"""
This type stub file was generated by pyright.
"""

import networkx as nx
import pandas as pd
from typing import Any, BinaryIO, Iterable, Optional, Set, Union

def setwrap(value: Any) -> Set[str]:
    """
    Returns a flattened and stringified set from the given object or iterable.

    For use in public functions which accept argmuents or kwargs that can be
    one object or a list of objects.
    """
    ...

def remove_node_attributes(G: nx.DiGraph, attributes: Union[str, Iterable[str]]): # -> DiGraph[Any]:
    """
    Return a copy of the graph with the given attributes
    deleted from all nodes.
    """
    ...

def detect_encoding(f: BinaryIO, limit: int = ...) -> str:
    """
    Return encoding of provided input stream.

    Most of the time it's unicode, but if we are unable to decode the input
    natively, use `chardet` to determine the encoding heuristically.
    """
    ...

def empty_df(columns: Optional[Iterable[str]] = ...) -> pd.DataFrame:
    ...

