"""
This type stub file was generated by pyright.
"""

import networkx as nx
from typing import Collection, Optional
from .gtfs import Feed
from .types import View

DEFAULT_NODES = ...
def extract_feed(inpath: str, outpath: str, view: View, config: nx.DiGraph = ...) -> str:
    """Extract a subset of a GTFS zip into a new file"""
    ...

def write_feed_dangerously(feed: Feed, outpath: str, nodes: Optional[Collection[str]] = ...) -> str:
    """Naively write a feed to a zipfile

    This function provides no sanity checks. Use it at
    your own risk.
    """
    ...

